### ISSUE TITLE
Accessibility checklist issues

### ISSUE THREAD

**Issue by femmebot** [18F/ntis-gov#22]
- [x] Let's talk links should have some descriptive properties added.
- [x] NTIS logo alt text should include "National Technical Information Service"
- [x] Department of Commerce seal needs proper alt text. Must include the same text on the image itself.
- [x] Alpha NTIS links in top bar need more contrast.
- [x] Set html lang to "en"
- [x] Sub Page is missing H1. Pages skip h3 heading.
- [x] Skip link is needed

**Comment by femmebot** [comment]
Let's Talk buttons deleted. #1 no longer applicable.
